<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VillaSeeder extends Seeder
{
    public function run(): void
    {
        $villas = [
            // ==========================================
            // OWNER 1 : DANIEL (Total 10 Villa)
            // ==========================================
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Senayan Asri',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Senayan',
                'kecamatan' => 'Kebayoran Baru',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2244,
                'longitude' => 106.8116,
                'harga' => 700000,
                'kapasitas' => 12,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000001',
                'instagram' => '@villasenayanasri',
                'facebook' => 'villa.senayan.asri',
                'tiktok' => '@villasenayanasri',
                'alamat' => 'Jl. Raya Senayan No. 1, Senayan, Kebayoran Baru, Jakarta',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Gunung Permai',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Gunung',
                'kecamatan' => 'Kebayoran Baru',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2234,
                'longitude' => 106.8126,
                'harga' => 2500000,
                'kapasitas' => 6,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000002',
                'instagram' => '@villagunungpermai',
                'facebook' => 'villa.gunung.permai',
                'tiktok' => '@villagunungpermai',
                'alamat' => 'Jl. Raya Gunung No. 2, Gunung, Kebayoran Baru, Jakarta',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Lembang Indah',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Lembang',
                'kecamatan' => 'Lembang',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8112,
                'longitude' => 107.6216,
                'harga' => 900000,
                'kapasitas' => 14,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000003',
                'instagram' => '@villalembangindah',
                'facebook' => 'villa.lembang.indah',
                'tiktok' => '@villalembangindah',
                'alamat' => 'Jl. Raya Lembang No. 3, Lembang, Lembang, Bandung',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Cikole Mewah',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Cikole',
                'kecamatan' => 'Lembang',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8102,
                'longitude' => 107.6226,
                'harga' => 2900000,
                'kapasitas' => 14,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000004',
                'instagram' => '@villacikolemewah',
                'facebook' => 'villa.cikole.mewah',
                'tiktok' => '@villacikolemewah',
                'alamat' => 'Jl. Raya Cikole No. 4, Cikole, Lembang, Bandung',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Cisarua Damai',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Cisarua',
                'kecamatan' => 'Cisarua',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.663,
                'longitude' => 106.941,
                'harga' => 2100000,
                'kapasitas' => 9,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 4,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000005',
                'instagram' => '@villacisaruadamai',
                'facebook' => 'villa.cisarua.damai',
                'tiktok' => '@villacisaruadamai',
                'alamat' => 'Jl. Raya Cisarua No. 5, Cisarua, Cisarua, Bogor',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Citeko Sejahtera',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Citeko',
                'kecamatan' => 'Cisarua',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.662,
                'longitude' => 106.942,
                'harga' => 1800000,
                'kapasitas' => 6,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 4,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000006',
                'instagram' => '@villacitekosejahtera',
                'facebook' => 'villa.citeko.sejahtera',
                'tiktok' => '@villacitekosejahtera',
                'alamat' => 'Jl. Raya Citeko No. 6, Citeko, Cisarua, Bogor',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Sosromenduran Bahagia',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Sosromenduran',
                'kecamatan' => 'Gedongtengen',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7895,
                'longitude' => 110.3688,
                'harga' => 1800000,
                'kapasitas' => 7,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000007',
                'instagram' => '@villasosromenduranbahagia',
                'facebook' => 'villa.sosromenduran.bahagia',
                'tiktok' => '@villasosromenduranbahagia',
                'alamat' => 'Jl. Raya Sosromenduran No. 7, Sosromenduran, Gedongtengen, Yogyakarta',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Hargobinangun Elok',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Hargobinangun',
                'kecamatan' => 'Pakem',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7885,
                'longitude' => 110.3698,
                'harga' => 1400000,
                'kapasitas' => 9,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000008',
                'instagram' => '@villahargobinangunelok',
                'facebook' => 'villa.hargobinangun.elok',
                'tiktok' => '@villahargobinangunelok',
                'alamat' => 'Jl. Raya Hargobinangun No. 8, Hargobinangun, Pakem, Yogyakarta',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Pekayon Jaya Anggun',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Pekayon Jaya',
                'kecamatan' => 'Bekasi Selatan',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2528,
                'longitude' => 106.9886,
                'harga' => 1500000,
                'kapasitas' => 7,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000009',
                'instagram' => '@villapekayonjayaanggun',
                'facebook' => 'villa.pekayon.jaya.anggun',
                'tiktok' => '@villapekayonjayaanggun',
                'alamat' => 'Jl. Raya Pekayon Jaya No. 9, Pekayon Jaya, Bekasi Selatan, Bekasi',
            ],
            [
                'id_owner' => 1,
                'nama_villa' => 'Villa Marga Jaya Megah',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Marga Jaya',
                'kecamatan' => 'Bekasi Selatan',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2518,
                'longitude' => 106.9896,
                'harga' => 600000,
                'kapasitas' => 8,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000010',
                'instagram' => '@villamargajayamegah',
                'facebook' => 'villa.marga.jaya.megah',
                'tiktok' => '@villamargajayamegah',
                'alamat' => 'Jl. Raya Marga Jaya No. 10, Marga Jaya, Bekasi Selatan, Bekasi',
            ],
            // ==========================================
            // OWNER 2 : KHOIR (Total 10 Villa)
            // ==========================================
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Cipete Selatan Nirwana',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Cipete Selatan',
                'kecamatan' => 'Cilandak',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2224,
                'longitude' => 106.8136,
                'harga' => 1500000,
                'kapasitas' => 15,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000011',
                'instagram' => '@villacipeteselatannirwana',
                'facebook' => 'villa.cipete.selatan.nirwana',
                'tiktok' => '@villacipeteselatannirwana',
                'alamat' => 'Jl. Raya Cipete Selatan No. 11, Cipete Selatan, Cilandak, Jakarta',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Lebak Bulus Eksotis',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Lebak Bulus',
                'kecamatan' => 'Cilandak',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2214,
                'longitude' => 106.8146,
                'harga' => 500000,
                'kapasitas' => 6,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000012',
                'instagram' => '@villalebakbuluseksotis',
                'facebook' => 'villa.lebak.bulus.eksotis',
                'tiktok' => '@villalebakbuluseksotis',
                'alamat' => 'Jl. Raya Lebak Bulus No. 12, Lebak Bulus, Cilandak, Jakarta',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Cihideung Pesona',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Cihideung',
                'kecamatan' => 'Parongpong',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8092,
                'longitude' => 107.6236,
                'harga' => 2600000,
                'kapasitas' => 13,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000013',
                'instagram' => '@villacihideungpesona',
                'facebook' => 'villa.cihideung.pesona',
                'tiktok' => '@villacihideungpesona',
                'alamat' => 'Jl. Raya Cihideung No. 13, Cihideung, Parongpong, Bandung',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Cigugur Girang Kencana',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Cigugur Girang',
                'kecamatan' => 'Parongpong',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8082,
                'longitude' => 107.6246,
                'harga' => 2400000,
                'kapasitas' => 13,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000014',
                'instagram' => '@villacigugurgirangkencana',
                'facebook' => 'villa.cigugur.girang.kencana',
                'tiktok' => '@villacigugurgirangkencana',
                'alamat' => 'Jl. Raya Cigugur Girang No. 14, Cigugur Girang, Parongpong, Bandung',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Sukakarya Lestari',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Sukakarya',
                'kecamatan' => 'Megamendung',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.661,
                'longitude' => 106.943,
                'harga' => 2600000,
                'kapasitas' => 5,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 4,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000015',
                'instagram' => '@villasukakaryalestari',
                'facebook' => 'villa.sukakarya.lestari',
                'tiktok' => '@villasukakaryalestari',
                'alamat' => 'Jl. Raya Sukakarya No. 15, Sukakarya, Megamendung, Bogor',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Cipayung Girang Sentosa',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Cipayung Girang',
                'kecamatan' => 'Megamendung',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.66,
                'longitude' => 106.944,
                'harga' => 2100000,
                'kapasitas' => 12,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000016',
                'instagram' => '@villacipayunggirangsentosa',
                'facebook' => 'villa.cipayung.girang.sentosa',
                'tiktok' => '@villacipayunggirangsentosa',
                'alamat' => 'Jl. Raya Cipayung Girang No. 16, Cipayung Girang, Megamendung, Bogor',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Purwobinangun Ceria',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Purwobinangun',
                'kecamatan' => 'Pakem',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7875,
                'longitude' => 110.3708,
                'harga' => 700000,
                'kapasitas' => 15,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000017',
                'instagram' => '@villapurwobinangunceria',
                'facebook' => 'villa.purwobinangun.ceria',
                'tiktok' => '@villapurwobinangunceria',
                'alamat' => 'Jl. Raya Purwobinangun No. 17, Purwobinangun, Pakem, Yogyakarta',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Wukirsari Mentari',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Wukirsari',
                'kecamatan' => 'Cangkringan',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7865,
                'longitude' => 110.3718,
                'harga' => 1100000,
                'kapasitas' => 14,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000018',
                'instagram' => '@villawukirsarimentari',
                'facebook' => 'villa.wukirsari.mentari',
                'tiktok' => '@villawukirsarimentari',
                'alamat' => 'Jl. Raya Wukirsari No. 18, Wukirsari, Cangkringan, Yogyakarta',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Harapan Baru Cantika',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Harapan Baru',
                'kecamatan' => 'Bekasi Utara',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2508,
                'longitude' => 106.9906,
                'harga' => 2600000,
                'kapasitas' => 4,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000019',
                'instagram' => '@villaharapanbarucantika',
                'facebook' => 'villa.harapan.baru.cantika',
                'tiktok' => '@villaharapanbarucantika',
                'alamat' => 'Jl. Raya Harapan Baru No. 19, Harapan Baru, Bekasi Utara, Bekasi',
            ],
            [
                'id_owner' => 2,
                'nama_villa' => 'Villa Perwira Asoka',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Perwira',
                'kecamatan' => 'Bekasi Utara',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2498,
                'longitude' => 106.9916,
                'harga' => 1800000,
                'kapasitas' => 5,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000020',
                'instagram' => '@villaperwiraasoka',
                'facebook' => 'villa.perwira.asoka',
                'tiktok' => '@villaperwiraasoka',
                'alamat' => 'Jl. Raya Perwira No. 20, Perwira, Bekasi Utara, Bekasi',
            ],
            // ==========================================
            // OWNER 3 : SHABIL (Total 10 Villa)
            // ==========================================
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Bangka Melati',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Bangka',
                'kecamatan' => 'Mampang Prapatan',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2204,
                'longitude' => 106.8156,
                'harga' => 1800000,
                'kapasitas' => 14,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000021',
                'instagram' => '@villabangkamelati',
                'facebook' => 'villa.bangka.melati',
                'tiktok' => '@villabangkamelati',
                'alamat' => 'Jl. Raya Bangka No. 21, Bangka, Mampang Prapatan, Jakarta',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Tegal Parang Cendana',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Tegal Parang',
                'kecamatan' => 'Mampang Prapatan',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2194,
                'longitude' => 106.8166,
                'harga' => 2800000,
                'kapasitas' => 5,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 4,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000022',
                'instagram' => '@villategalparangcendana',
                'facebook' => 'villa.tegal.parang.cendana',
                'tiktok' => '@villategalparangcendana',
                'alamat' => 'Jl. Raya Tegal Parang No. 22, Tegal Parang, Mampang Prapatan, Jakarta',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Jambudipa Kenanga',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Jambudipa',
                'kecamatan' => 'Cisarua',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8072,
                'longitude' => 107.6256,
                'harga' => 2400000,
                'kapasitas' => 13,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000023',
                'instagram' => '@villajambudipakenanga',
                'facebook' => 'villa.jambudipa.kenanga',
                'tiktok' => '@villajambudipakenanga',
                'alamat' => 'Jl. Raya Jambudipa No. 23, Jambudipa, Cisarua, Bandung',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Tugumukti Mawar',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Tugumukti',
                'kecamatan' => 'Cisarua',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8062,
                'longitude' => 107.6266,
                'harga' => 1300000,
                'kapasitas' => 10,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000024',
                'instagram' => '@villatugumuktimawar',
                'facebook' => 'villa.tugumukti.mawar',
                'tiktok' => '@villatugumuktimawar',
                'alamat' => 'Jl. Raya Tugumukti No. 24, Tugumukti, Cisarua, Bandung',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Banjarwangi Dahlia',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Banjarwangi',
                'kecamatan' => 'Ciawi',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.659,
                'longitude' => 106.945,
                'harga' => 800000,
                'kapasitas' => 9,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000025',
                'instagram' => '@villabanjarwangidahlia',
                'facebook' => 'villa.banjarwangi.dahlia',
                'tiktok' => '@villabanjarwangidahlia',
                'alamat' => 'Jl. Raya Banjarwangi No. 25, Banjarwangi, Ciawi, Bogor',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Bendungan Teratai',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Bendungan',
                'kecamatan' => 'Ciawi',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.658,
                'longitude' => 106.946,
                'harga' => 1200000,
                'kapasitas' => 13,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000026',
                'instagram' => '@villabendunganteratai',
                'facebook' => 'villa.bendungan.teratai',
                'tiktok' => '@villabendunganteratai',
                'alamat' => 'Jl. Raya Bendungan No. 26, Bendungan, Ciawi, Bogor',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Umbulharjo Harmoni',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Umbulharjo',
                'kecamatan' => 'Cangkringan',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7855,
                'longitude' => 110.3728,
                'harga' => 2800000,
                'kapasitas' => 4,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000027',
                'instagram' => '@villaumbulharjoharmoni',
                'facebook' => 'villa.umbulharjo.harmoni',
                'tiktok' => '@villaumbulharjoharmoni',
                'alamat' => 'Jl. Raya Umbulharjo No. 27, Umbulharjo, Cangkringan, Yogyakarta',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Girikerto Damar',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Girikerto',
                'kecamatan' => 'Turi',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7845,
                'longitude' => 110.3738,
                'harga' => 900000,
                'kapasitas' => 4,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000028',
                'instagram' => '@villagirikertodamar',
                'facebook' => 'villa.girikerto.damar',
                'tiktok' => '@villagirikertodamar',
                'alamat' => 'Jl. Raya Girikerto No. 28, Girikerto, Turi, Yogyakarta',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Jaka Sampurna Cemara',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Jaka Sampurna',
                'kecamatan' => 'Bekasi Barat',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2488,
                'longitude' => 106.9926,
                'harga' => 1200000,
                'kapasitas' => 8,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 4,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000029',
                'instagram' => '@villajakasampurnacemara',
                'facebook' => 'villa.jaka.sampurna.cemara',
                'tiktok' => '@villajakasampurnacemara',
                'alamat' => 'Jl. Raya Jaka Sampurna No. 29, Jaka Sampurna, Bekasi Barat, Bekasi',
            ],
            [
                'id_owner' => 3,
                'nama_villa' => 'Villa Bintara Pinus',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Bintara',
                'kecamatan' => 'Bekasi Barat',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2478,
                'longitude' => 106.9936,
                'harga' => 500000,
                'kapasitas' => 5,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000030',
                'instagram' => '@villabintarapinus',
                'facebook' => 'villa.bintara.pinus',
                'tiktok' => '@villabintarapinus',
                'alamat' => 'Jl. Raya Bintara No. 30, Bintara, Bekasi Barat, Bekasi',
            ],
            // ==========================================
            // OWNER 4 : FURQON (Total 10 Villa)
            // ==========================================
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Cikoko Kabut',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Cikoko',
                'kecamatan' => 'Pancoran',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2184,
                'longitude' => 106.8176,
                'harga' => 2400000,
                'kapasitas' => 9,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000031',
                'instagram' => '@villacikokokabut',
                'facebook' => 'villa.cikoko.kabut',
                'tiktok' => '@villacikokokabut',
                'alamat' => 'Jl. Raya Cikoko No. 31, Cikoko, Pancoran, Jakarta',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Kalibata Awan',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Kalibata',
                'kecamatan' => 'Pancoran',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2174,
                'longitude' => 106.8186,
                'harga' => 500000,
                'kapasitas' => 8,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000032',
                'instagram' => '@villakalibataawan',
                'facebook' => 'villa.kalibata.awan',
                'tiktok' => '@villakalibataawan',
                'alamat' => 'Jl. Raya Kalibata No. 32, Kalibata, Pancoran, Jakarta',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Panundaan Bukit',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Panundaan',
                'kecamatan' => 'Ciwidey',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8052,
                'longitude' => 107.6276,
                'harga' => 1600000,
                'kapasitas' => 6,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000033',
                'instagram' => '@villapanundaanbukit',
                'facebook' => 'villa.panundaan.bukit',
                'tiktok' => '@villapanundaanbukit',
                'alamat' => 'Jl. Raya Panundaan No. 33, Panundaan, Ciwidey, Bandung',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Lebakmuncang Lembah',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Lebakmuncang',
                'kecamatan' => 'Ciwidey',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8042,
                'longitude' => 107.6286,
                'harga' => 1000000,
                'kapasitas' => 14,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000034',
                'instagram' => '@villalebakmuncanglembah',
                'facebook' => 'villa.lebakmuncang.lembah',
                'tiktok' => '@villalebakmuncanglembah',
                'alamat' => 'Jl. Raya Lebakmuncang No. 34, Lebakmuncang, Ciwidey, Bandung',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Ciburayut Taman',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Ciburayut',
                'kecamatan' => 'Cigombong',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.657,
                'longitude' => 106.947,
                'harga' => 1800000,
                'kapasitas' => 9,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000035',
                'instagram' => '@villaciburayuttaman',
                'facebook' => 'villa.ciburayut.taman',
                'tiktok' => '@villaciburayuttaman',
                'alamat' => 'Jl. Raya Ciburayut No. 35, Ciburayut, Cigombong, Bogor',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Watesjaya Surya',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Watesjaya',
                'kecamatan' => 'Cigombong',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.656,
                'longitude' => 106.948,
                'harga' => 2500000,
                'kapasitas' => 10,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000036',
                'instagram' => '@villawatesjayasurya',
                'facebook' => 'villa.watesjaya.surya',
                'tiktok' => '@villawatesjayasurya',
                'alamat' => 'Jl. Raya Watesjaya No. 36, Watesjaya, Cigombong, Bogor',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Wonokerto Cahaya',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Wonokerto',
                'kecamatan' => 'Turi',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7835,
                'longitude' => 110.3748,
                'harga' => 2500000,
                'kapasitas' => 8,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000037',
                'instagram' => '@villawonokertocahaya',
                'facebook' => 'villa.wonokerto.cahaya',
                'tiktok' => '@villawonokertocahaya',
                'alamat' => 'Jl. Raya Wonokerto No. 37, Wonokerto, Turi, Yogyakarta',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Donokerto Mutiara',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Donokerto',
                'kecamatan' => 'Turi',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7825,
                'longitude' => 110.3758,
                'harga' => 1400000,
                'kapasitas' => 8,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000038',
                'instagram' => '@villadonokertomutiara',
                'facebook' => 'villa.donokerto.mutiara',
                'tiktok' => '@villadonokertomutiara',
                'alamat' => 'Jl. Raya Donokerto No. 38, Donokerto, Turi, Yogyakarta',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Margahayu Permata',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Margahayu',
                'kecamatan' => 'Bekasi Timur',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2468,
                'longitude' => 106.9946,
                'harga' => 2900000,
                'kapasitas' => 12,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000039',
                'instagram' => '@villamargahayupermata',
                'facebook' => 'villa.margahayu.permata',
                'tiktok' => '@villamargahayupermata',
                'alamat' => 'Jl. Raya Margahayu No. 39, Margahayu, Bekasi Timur, Bekasi',
            ],
            [
                'id_owner' => 4,
                'nama_villa' => 'Villa Duren Jaya Zamrud',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Duren Jaya',
                'kecamatan' => 'Bekasi Timur',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2458,
                'longitude' => 106.9956,
                'harga' => 1800000,
                'kapasitas' => 12,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000040',
                'instagram' => '@villadurenjayazamrud',
                'facebook' => 'villa.duren.jaya.zamrud',
                'tiktok' => '@villadurenjayazamrud',
                'alamat' => 'Jl. Raya Duren Jaya No. 40, Duren Jaya, Bekasi Timur, Bekasi',
            ],
            // ==========================================
            // OWNER 5 : NABILA (Total 10 Villa)
            // ==========================================
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Menteng Dalam Berlian',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Menteng Dalam',
                'kecamatan' => 'Tebet',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2164,
                'longitude' => 106.8196,
                'harga' => 700000,
                'kapasitas' => 12,
                'jumlah_kamar' => 2,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000041',
                'instagram' => '@villamentengdalamberlian',
                'facebook' => 'villa.menteng.dalam.berlian',
                'tiktok' => '@villamentengdalamberlian',
                'alamat' => 'Jl. Raya Menteng Dalam No. 41, Menteng Dalam, Tebet, Jakarta',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Karet Kuningan Intan',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Jakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Jakarta',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'provinsi' => 'DKI Jakarta',
                'latitude' => -6.2154,
                'longitude' => 106.8206,
                'harga' => 1900000,
                'kapasitas' => 7,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 1,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000042',
                'instagram' => '@villakaretkuninganintan',
                'facebook' => 'villa.karet.kuningan.intan',
                'tiktok' => '@villakaretkuninganintan',
                'alamat' => 'Jl. Raya Karet Kuningan No. 42, Karet Kuningan, Setiabudi, Jakarta',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Patengan Cendrawasih',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Patengan',
                'kecamatan' => 'Rancabali',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8032,
                'longitude' => 107.6296,
                'harga' => 1800000,
                'kapasitas' => 4,
                'jumlah_kamar' => 6,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000043',
                'instagram' => '@villapatengancendrawasih',
                'facebook' => 'villa.patengan.cendrawasih',
                'tiktok' => '@villapatengancendrawasih',
                'alamat' => 'Jl. Raya Patengan No. 43, Patengan, Rancabali, Bandung',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Alamendah Garuda',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bandung, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bandung',
                'kelurahan' => 'Alamendah',
                'kecamatan' => 'Rancabali',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.8022,
                'longitude' => 107.6306,
                'harga' => 2100000,
                'kapasitas' => 11,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 5,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000044',
                'instagram' => '@villaalamendahgaruda',
                'facebook' => 'villa.alamendah.garuda',
                'tiktok' => '@villaalamendahgaruda',
                'alamat' => 'Jl. Raya Alamendah No. 44, Alamendah, Rancabali, Bandung',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Caringin Nusantara',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Caringin',
                'kecamatan' => 'Caringin',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.655,
                'longitude' => 106.949,
                'harga' => 2600000,
                'kapasitas' => 4,
                'jumlah_kamar' => 5,
                'jumlah_kamar_mandi' => 4,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000045',
                'instagram' => '@villacaringinnusantara',
                'facebook' => 'villa.caringin.nusantara',
                'tiktok' => '@villacaringinnusantara',
                'alamat' => 'Jl. Raya Caringin No. 45, Caringin, Caringin, Bogor',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Cimande Pelangi',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bogor, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bogor',
                'kelurahan' => 'Cimande',
                'kecamatan' => 'Caringin',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.654,
                'longitude' => 106.95,
                'harga' => 2400000,
                'kapasitas' => 8,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000046',
                'instagram' => '@villacimandepelangi',
                'facebook' => 'villa.cimande.pelangi',
                'tiktok' => '@villacimandepelangi',
                'alamat' => 'Jl. Raya Cimande No. 46, Cimande, Caringin, Bogor',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Sukoharjo Senja',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Sukoharjo',
                'kecamatan' => 'Ngaglik',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7815,
                'longitude' => 110.3768,
                'harga' => 2300000,
                'kapasitas' => 6,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000047',
                'instagram' => '@villasukoharjosenja',
                'facebook' => 'villa.sukoharjo.senja',
                'tiktok' => '@villasukoharjosenja',
                'alamat' => 'Jl. Raya Sukoharjo No. 47, Sukoharjo, Ngaglik, Yogyakarta',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Sardonoharjo Fajar',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Yogyakarta, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Yogyakarta',
                'kelurahan' => 'Sardonoharjo',
                'kecamatan' => 'Ngaglik',
                'provinsi' => 'DI Yogyakarta',
                'latitude' => -7.7805,
                'longitude' => 110.3778,
                'harga' => 2100000,
                'kapasitas' => 8,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 2,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000048',
                'instagram' => '@villasardonoharjofajar',
                'facebook' => 'villa.sardonoharjo.fajar',
                'tiktok' => '@villasardonoharjofajar',
                'alamat' => 'Jl. Raya Sardonoharjo No. 48, Sardonoharjo, Ngaglik, Yogyakarta',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Jatibening Embun',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Jatibening',
                'kecamatan' => 'Pondok Gede',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2448,
                'longitude' => 106.9966,
                'harga' => 1000000,
                'kapasitas' => 14,
                'jumlah_kamar' => 3,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000049',
                'instagram' => '@villajatibeningembun',
                'facebook' => 'villa.jatibening.embun',
                'tiktok' => '@villajatibeningembun',
                'alamat' => 'Jl. Raya Jatibening No. 49, Jatibening, Pondok Gede, Bekasi',
            ],
            [
                'id_owner' => 5,
                'nama_villa' => 'Villa Jaticempaka Bahari',
                'deskripsi' => 'Villa nyaman dan bersih di daerah Bekasi, cocok untuk liburan keluarga atau acara kantor.',
                'kota' => 'Bekasi',
                'kelurahan' => 'Jaticempaka',
                'kecamatan' => 'Pondok Gede',
                'provinsi' => 'Jawa Barat',
                'latitude' => -6.2438,
                'longitude' => 106.9976,
                'harga' => 700000,
                'kapasitas' => 7,
                'jumlah_kamar' => 4,
                'jumlah_kamar_mandi' => 3,
                'status' => 'disetujui',
                'ulasan' => null,
                'whatsapp' => '081200000050',
                'instagram' => '@villajaticempakabahari',
                'facebook' => 'villa.jaticempaka.bahari',
                'tiktok' => '@villajaticempakabahari',
                'alamat' => 'Jl. Raya Jaticempaka No. 50, Jaticempaka, Pondok Gede, Bekasi',
            ],
        ];

        foreach ($villas as $villaData) {
            $id = DB::table('villa')->insertGetId(array_merge($villaData, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));

            $fasilitasList = [
                'Kolam Renang',
                'WiFi Gratis',
                'Sarapan',
                'Parkir Luas',
                'AC Setiap Kamar',
            ];

            foreach ($fasilitasList as $fasilitas) {
                DB::table('fasilitas_villa')->insert([
                    'id_villa' => $id,
                    'fasilitas' => $fasilitas,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }

        $this->command->info('VillaSeeders: Berhasil (50 Villa Dibuat)');
    }
}
